### ISSUE TITLE
Play button not working on iOS 17.3.1

### ISSUE THREAD

**Issue by fosterc1** [cgkineo/adapt-simpleVideoBranching#12]
### Subject of the issue/enhancement/features
The play button overlaid on the video does not work on iOS touch devices

### Your environment
* version (AT v0.11.2/Framework v5.35.7)
* which browser and its version
* device(s) + operating system(s)

### Steps to reproduce
We have added an initial video and alternative correct & incorrect videos, when previewing the elearning the play button overlaid on the poster/video does not play or pause the video.

### Expected behaviour
As per the media component, the play button overlaid on the video should play/pause the video on all devices.
![IMG_0232](https://github.com/cgkineo/adapt-simpleVideoBranching/assets/29701150/e3eb310c-4c73-447d-9459-ed7fb93430e6)
![IMG_2259](https://github.com/cgkineo/adapt-simpleVideoBranching/assets/29701150/5e98aec6-72f4-42ed-b647-966638ce2bd8)

### Actual behaviour
Tell us what happens instead

**Comment by oliverfoster** [comment]
Could you list the touch devices you've tested on please.

**Comment by fosterc1** [comment]
Hello 

Tested on iPhone 14 Pro and iPad Pro running iOS 17.3.1 and Safari.

Thanks
