### ISSUE TITLE
Nothing displaying when previewing and was working before recent upgrade.

### ISSUE THREAD

**Issue by mldaq** [cgkineo/adapt-simpleVideoBranching#7]
### Subject of the issue/enhancement/features
Nothing displaying when previewing and was working before recent upgrade.

### Your environment
* version (AT/Framework) - (O.11.2/v5.32.6)
* which browser and its version - (MS Edge - Version 118.0.2088.46 /Chrome Version 118.0.5993.71)
* device(s) + operating system(s) - PC Windows 10 Enterprise

### Issue
Nothing renders - when previewing. There is a blank screen, and it was working.

### Screenshots (if you can)
![image](https://github.com/cgkineo/adapt-simpleVideoBranching/assets/15389177/7ed52ed6-0e94-4933-9212-a8548689bc2f)

**Comment by mldaq** [comment]
![image](https://github.com/cgkineo/adapt-simpleVideoBranching/assets/15389177/347c08bf-df86-4a6e-9f89-5f96a5b9a7eb)

**Comment by fosterc1** [comment]
Can confirm this is not showing anything in fw v5.33.5, is there anything that can be done to resolve this?

Cheers
